version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-scraper-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_DB_TYPE=faiss
      - VECTOR_DB_PATH=/app/data/vector_db
    restart: unless-stopped

  # Uncomment to enable Qdrant vector database if needed
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   container_name: news-scraper-qdrant
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - ./data/qdrant_storage:/qdrant/storage
  #   environment:
  #     - QDRANT__SERVICE__GRPC_PORT=6334
  #   restart: unless-stopped
